using System.Collections;
using FindTheDifference.obj;

namespace FindTheDifference;

class Program
{
    static void Main(string[] args)
    {
        // Given Two Strings 'S' and 'T'
        // T is generated by random shuffling string S and then add one more letter. 
        // Our goal is to find the difference. 

        string s = "a";
        string t = "aa"; 

        System.Console.WriteLine(Solution.solution(s,t));
    
    }
}
